### ISSUE TITLE
Implement login functionality (10h)

### ISSUE THREAD

**Issue by joelkuppart** [SuperTurban/ekm_mobiilposm2ng#41]
**Subtask of:** [https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/6](https://github.com/SuperTurban/ekm_mobiilposm2ng/issues/6)

**To do:**
- [x] Web app UI: username and password field, submit button.

- [x] Database: Create a table to keep data about users (fields: ID, username, (encrypted) password)

- [x] Back-end: Validating the inserted user credentials.

**Comment by SuperTurban** [comment]
Basic authentication added.
